# Generated by Django 5.1.6 on 2025-02-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_ask_user_alter_bid_user_alter_sale_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
    ]
