# Generated by Django 5.1.6 on 2025-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_sale_buyer_sale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.CharField(blank=True, choices=[('auction', 'Auction'), ('sales', 'Sales')], default=None, null=True),
        ),
    ]
