# Generated by Django 5.1.6 on 2025-03-04 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_currency_client_client_currency_and_more'),
        ('auctions', '0003_remove_auction_seller'),
        ('cards', '0016_cardentity_on_sale'),
        ('market', '0005_bid_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('auction_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctionresult')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_buyer', to='accounts.client')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_seller', to='accounts.client')),
            ],
        ),
    ]
