# Generated by Django 5.1.6 on 2025-04-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_alter_collections_added_on'),
        ('market', '0006_auctionsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.grade'),
        ),
        migrations.AddField(
            model_name='bid',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.grade'),
        ),
        migrations.AddField(
            model_name='sale',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.grade'),
        ),
    ]
