# Generated by Django 5.1.6 on 2025-02-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_participants', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('booster_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.boosterbox')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='CasinoSaleParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.cardentity')),
                ('casino_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casinos.casinosale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
