# Generated by Django 5.1.6 on 2025-02-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinosale',
            name='is_active',
        ),
    ]
