# Generated by Django 5.1.6 on 2025-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_remove_casinosale_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinosale',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
