# Generated by Django 5.1.6 on 2025-02-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0003_casinosale_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinosale',
            name='image',
        ),
    ]
