# Generated by Django 5.1.6 on 2025-02-13 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0004_remove_casinosale_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinosale',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='casinosale',
            name='started_at',
        ),
        migrations.AddField(
            model_name='casinosale',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 9, 19, 58, 977728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='casinosale',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 9, 19, 58, 977716, tzinfo=datetime.timezone.utc)),
        ),
    ]
