# Generated by Django 5.1.6 on 2025-02-13 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0005_remove_casinosale_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinosale',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='casinosale',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
