# Generated by Django 5.1.6 on 2025-03-17 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0006_alter_casinosale_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinosaleparticipant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
