# Generated by Django 5.1.6 on 2025-02-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='seller',
        ),
    ]
