# Generated by Django 5.1.6 on 2025-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_card_id_remove_cardset_set_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.CharField(max_length=200),
        ),
    ]
