# Generated by Django 5.1.6 on 2025-02-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterpack',
            name='cards',
            field=models.ManyToManyField(to='cards.card'),
        ),
        migrations.AlterField(
            model_name='cardentity',
            name='ask_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cards',
            field=models.ManyToManyField(to='cards.card'),
        ),
    ]
