# Generated by Django 5.1.6 on 2025-02-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_boosterpack_cards_alter_cardentity_ask_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosterbox',
            name='total_packs',
        ),
    ]
