# Generated by Django 5.1.6 on 2025-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_boosterbox_total_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosterbox',
            name='image',
            field=models.ImageField(blank=True, upload_to='booster-box-images'),
        ),
    ]
