# Generated by Django 5.1.6 on 2025-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_boosterbox_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterbox',
            name='image',
            field=models.ImageField(blank=True, upload_to='booster-box-images/'),
        ),
    ]
