# Generated by Django 5.1.6 on 2025-02-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_currency_client_client_currency_and_more'),
        ('cards', '0007_alter_boosterbox_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cards', models.ManyToManyField(to='cards.card')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
