# Generated by Django 5.1.6 on 2025-02-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
