# Generated by Django 5.1.6 on 2025-02-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_collections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boosterbox',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.grade'),
        ),
    ]
