# Generated by Django 5.1.6 on 2025-02-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_boosterbox_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.grade'),
        ),
    ]
