# Generated by Django 5.1.6 on 2025-02-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, null=True),
        ),
    ]
