# Generated by Django 5.1.6 on 2025-02-26 09:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_card_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='ancient_trait',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='attacks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardmarket',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='convertedRetreatCost',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='hp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='legalities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='national_pokedex_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='regulation_mark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='resistances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='retreat_cost',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='tcgplayer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='card',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='card',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
