# Generated by Django 5.1.6 on 2025-02-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_card_added_on_alter_card_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
