# Generated by Django 5.1.6 on 2025-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_card_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardentity',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
