# Generated by Django 5.1.6 on 2025-03-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_currency_client_client_currency_and_more'),
        ('cards', '0017_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
    ]
