# Generated by Django 5.1.6 on 2025-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_portfolio_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection-images/'),
        ),
    ]
