# Generated by Django 5.1.6 on 2025-03-20 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_collections_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
