# Generated by Django 5.1.6 on 2025-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_collections_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
