# Generated by Django 5.1.6 on 2025-05-01 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_raw_grade_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardentity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
