# Generated by Django 5.1.6 on 2025-05-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_cardentity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boosterbox',
            name='image',
            field=models.ImageField(upload_to='booster-box-images/'),
        ),
    ]
