# Generated by Django 5.1.6 on 2025-02-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_collections_name'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbid',
            name='sale',
        ),
        migrations.AddField(
            model_name='salesbid',
            name='card',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
    ]
