# Generated by Django 5.1.6 on 2025-04-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_alter_collections_added_on'),
        ('sales', '0002_remove_salesbid_sale_salesbid_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbid',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.grade'),
        ),
    ]
